language: java
jdk:
  - openjdk8
branches:
  only:
    - master
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_deploy:
  - zip -r tairu-webservice *
  - mkdir -p deploy
  - mv tairu-webservice.zip deploy/tairu-webservice.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: tairu-webservice-build
    region: ap-northeast-2
    skip_clenaup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
notifications:
  email:
    recipients:
      - 'dongwook.kim@monogodb.com'
